ucb-bar/hammer

src/addons/core-generator/rocket-chip/rules.mk

I was less clear if this is how you wanted this done so I'm gonna PR it first.

Add RC_CORE_ADDONS variable for CORE_DIR users with rocket-chip addons

---

Makefile

This makes it easier to update firrtl

Force PFPMP rebuild if firrtl changes

---

src/addons/synthesis/dc/rules.mk
src/addons/synthesis/dc/tools/run-synthesis
src/addons/synthesis/dc/vars.mk

We sometimes want to use various DC's compile/compile_ultra arguments.

Pass DC's compile/compile_ultra arguments

---

src/addons/par/icc/tools/icc_common.sh
src/addons/par/icc/vars.mk
src/addons/signoff-power/primetime/tools/run-primetime

We may want to merge it prior to #28.

Donggyu's fixes

---

.gitmodules

Makes it easier to run hammer out of the box

Add jsonschema submodule

---

src/hammer-shell/README.txt
src/hammer-vlsi/README.md
src/hammer-vlsi/defaults.yml
src/hammer-vlsi/entry.py
src/hammer-vlsi/generate_properties.py
src/hammer-vlsi/hammer_vlsi.py
src/hammer-vlsi/par/icc/__init__.py
src/hammer-vlsi/par/icc/defaults.yml
src/hammer-vlsi/par/icc/tools/run-par
src/hammer-vlsi/par/nop.py
src/hammer-vlsi/synthesis/dc/__init__.py
src/hammer_config/config_src.py
src/test/mypy.sh

Barebones place and route

---

.gitmodules

@donggyukim Thanks for your efforts and help :+1:

Goodbye, pcad

---

src/hammer-vlsi/hammer_vlsi.py
src/hammer-vlsi/synthesis/dc/__init__.py
src/hammer-vlsi/synthesis/dc/tools/run-synthesis
src/hammer-vlsi/synthesis/genus/__init__.py
src/hammer-vlsi/synthesis/genus/defaults.yml
src/hammer-vlsi/test.py

Synthesis with Genus in the new hammer-vlsi.

Genus synthesis

---

src/hammer-vlsi/hammer_vlsi.py
src/hammer-vlsi/par/icc/__init__.py
src/hammer-vlsi/par/icc/defaults.yml
src/hammer_config/config_src.py
src/hammer_config_test/test.py

- Implement prependlocal, transclude
- Support arrays of meta directives

Meta directive improvements

---

src/hammer-vlsi/cli_driver.py

In addition to ignoring null lists also ignore empty strings in a list

Don't add empty configs if given empty strings

---

src/hammer-vlsi/cli_driver.py

Allow the use of syn for the cli driver

---

src/hammer-vlsi/synthesis/genus/__init__.py

Missed this in my last changeset

with the new genus startup we write out sdc with view name

---

src/hammer-vlsi/par/innovus/__init__.py
src/hammer-vlsi/synthesis/genus/__init__.py

add max-threads support for cadence tools

---

src/hammer-vlsi/defaults.yml
src/hammer-vlsi/par/innovus/__init__.py
src/hammer-vlsi/technology/saed32/defaults.yml
src/hammer-vlsi/technology/tsmc180osu/defaults.yml

Not sure if this is the right way to give options a default or if I should have nothing and then a check in the emission

give a design node parameter and pass to innovus

---

src/hammer-tech/schema.json
src/hammer-vlsi/hammer_vlsi.py

Just to start the mmmc stuff going, still got a lot of other options to add

Add qrc TechFile support and add to cadence library setup

---

.mailmap
src/hammer-vlsi/cli_driver.py
src/hammer-vlsi/hammer_vlsi.py
src/hammer-vlsi/par/icc/__init__.py
src/hammer-vlsi/par/innovus/__init__.py
src/hammer-vlsi/par/nop.py
src/hammer-vlsi/synthesis/dc/__init__.py
src/hammer-vlsi/synthesis/genus/__init__.py
src/hammer-vlsi/synthesis/genus/defaults.yml
src/hammer-vlsi/synthesis/mocksynth/__init__.py
src/hammer-vlsi/synthesis/mocksynth/defaults.yml
src/hammer-vlsi/technology/nop/defaults.yml
src/hammer-vlsi/technology/nop/nop.tech.json
src/hammer-vlsi/test.py
src/hammer_config/config_src.py
src/hammer_config/yaml2json.py

Genus is tested and appears to work. Innovus is next, hoping to get it done by tonight.
None of the other plugins are ported to this new style yet - they will come afterwards.
@colinschmidt Preliminary thoughts?

Modularize hammer plugins into hookable/pausable steps

---

src/hammer-vlsi/hammer_vlsi.py

use atexit to kill subprocs

---

src/hammer-vlsi/test.py

Add test to insert hook before step1

---

src/hammer-vlsi/hammer_vlsi.py
src/hammer-vlsi/test.py

Test hook on hook

---

src/hammer-vlsi/hammer_vlsi.py

add ability to set port/pin name of clocks

---

src/hammer-vlsi/hammer_vlsi.py
src/hammer-vlsi/par/innovus/__init__.py
src/hammer-vlsi/synthesis/genus/__init__.py

Just some utility thing I needed/wanted

Non verbose append

---

src/hammer-vlsi/synthesis/genus/__init__.py

I couldn't come up with a good name for the option to control this and wasn't quite sure you would want to disable it, so feedback on either would be good.

Make sure you have all sources included

---

src/hammer-vlsi/defaults.yml
src/hammer-vlsi/hammer_vlsi.py

Example usage at https://github.com/ucb-bar/hammer-nda-saed32-aspire-synthesis/blob/master/SodorTile.yml

Implement floorplan constraint infrastructure

---

src/hammer-vlsi/defaults.yml
src/hammer-vlsi/hammer_vlsi.py

This seems to work for my use case.

Add MMMC corners json and setup scripts

---

src/hammer-shell/hammer-vlsi
src/hammer-vlsi/cli_driver.py
src/hammer-vlsi/hammer_vlsi.py

Make cli_driver a class

---

src/hammer-vlsi/test.py

Add tests for first hook and fix context manager's return from __exit__() in case of error

---

src/hammer_config/config_src.py
src/hammer_config_test/test.py

Now we can specify JSON strings for variables like vlsi.inputs.placement_constraints.

Implement json2list

---

src/hammer-tech/schema.json
src/hammer-vlsi/defaults.yml

Haven't changed this file before but I think this is what I want.

Add site tech parameter to schema

---

src/hammer-vlsi/cli_driver.py

Makes custom action creation easier and allows for a custom post_load hook

Refactor action map functions

---

src/hammer-vlsi/cli_driver.py

Add a synthesis and par action

---

src/hammer-tech/schema.json
src/hammer-vlsi/hammer_vlsi_impl.py

Some SRAMs come with synthesizable wrappers

Add back support for verilog_synth

---

src/hammer-vlsi/cli_driver.py
src/hammer-vlsi/cli_driver_test.py
src/hammer-vlsi/hammer_vlsi_impl.py
src/hammer-vlsi/par/nop.py
src/hammer-vlsi/synthesis/mocksynth/__init__.py
src/hammer-vlsi/utils_test.py
src/test/mypy.sh
src/test/unittests.sh

And add a first unit test to CLIDriver

Dump intermediate configs in syn_par

---

src/hammer-vlsi/defaults.yml
src/hammer-vlsi/hammer_vlsi_impl.py

This creates an API to add blockages/obstructions to your placement constraints.
The three types of constraints simply reflect my current usage and could be expanded.

Floorplan obstructions API

---

src/hammer-vlsi/synthesis/vivado/__init__.py
src/hammer-vlsi/synthesis/vivado/prologue.tcl
src/hammer-vlsi/synthesis/vivado/run-synthesis

@edwardcwang 
Unless I'm wrong, Vivado doesn't seem to be kept up to date. Here's my attempt to get Vivado back up. Does this look reasonable? I only kind of know what's going on in here, so any feedback is welcome.

Work on Vivado to get it synthesizing for me

---

src/hammer-vlsi/hammer_vlsi/units.py

Typo mili->milli

---

src/hammer-tech/hammer_tech.py
src/hammer-vlsi/hammer_vlsi/driver.py
src/hammer-vlsi/test.py

This enables people to write comments in the tech plugins

Add the ability for tech plugins to use yaml

---

src/hammer_config/config_src.py
src/hammer_config_test/test.py

Allows settings to reference other settings arbitrarily.
Close #224

Implement crossref

---

src/hammer-tech/hammer_tech.py
src/hammer-tech/schema.json
src/hammer-vlsi/defaults.yml
src/hammer-vlsi/hammer_vlsi/driver.py
src/hammer-vlsi/hammer_vlsi/hammer_tool.py
src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py
src/hammer-vlsi/test.py

Dont use api

---

src/hammer-vlsi/hammer_vlsi/submit_command.py

Ensure LSF jobs are killed when hammer exits

---

src/hammer-vlsi/hammer_utils.py
src/hammer-vlsi/hammer_vlsi/cli_driver.py
src/hammer-vlsi/hammer_vlsi/hammer_tool.py
src/hammer-vlsi/utils_test.py

Refactor check_function_type to not raise an exception by default

---

README.md

First step to gathering documentation, as discussed?

Collect documentation links

---

src/hammer-tech/schema.json
src/hammer-vlsi/hammer_vlsi/hammer_tool.py

I noticed that TSMC45 needs this.
Warning: this is compared against #142

TLU+ map files

---

src/hammer-vlsi/hammer_vlsi/constraints.py
src/hammer-vlsi/hammer_vlsi/hooks.py
src/hammer-vlsi/hammer_vlsi/submit_command.py
src/hammer-vlsi/hammer_vlsi/units.py

No functional changes in this commit.

Code fluffing

---

src/hammer-tech/filters.py
src/hammer-tech/hammer_tech.py
src/hammer-tech/library_filter.py
src/hammer-tech/schema.json
src/hammer-vlsi/hammer_utils/__init__.py
src/hammer-vlsi/hammer_vlsi/hammer_tool.py
src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py
src/hammer-vlsi/test.py
src/hammer-vlsi/utils_test.py

Will be used in the macro sizes PR and reduces the amount of spaghetti code needed for it.

Technology and library filters refactor

---

src/hammer-tech/filters.py
src/hammer-tech/schema.json

Updated version of #209 meant to be merged to master.

Support TLU+ map files

---

src/hammer-vlsi/defaults.yml
src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py

Not tested yet but wanted to see if anyone had early feedback

Add power specification support

---

src/test/pylintrc

Not quite ready for automated checking yet since it's too noisy.

Check in pylintrc

---

src/hammer-tech/hammer_tech.py
src/hammer-vlsi/cli_driver_test.py
src/hammer-vlsi/defaults.yml
src/hammer-vlsi/hammer_vlsi/cli_driver.py
src/hammer-vlsi/tech_test.py

This is the Hammer side only. Floorplanning DSL side forthcoming.

Macro sizes API

---

src/hammer-vlsi/tech_test.py

Actually run tech_test

---

src/hammer-vlsi/hammer_vlsi/cli_driver.py
src/hammer-vlsi/hammer_vlsi/driver.py
src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py

This is useful if your hierarchical auto job fails in the middle and you need to restart it manually
Re-opening #291

Add hier-par-to-syn helper

---

src/hammer-vlsi/defaults.yml
src/hammer-vlsi/hammer_vlsi/constraints.py
src/hammer-vlsi/hammer_vlsi/hammer_tool.py
src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py

 Add generated clocks to clock API

---

src/hammer-vlsi/constraints_test.py
src/hammer-vlsi/defaults.yml
src/hammer-vlsi/hammer_vlsi/constraints.py
src/hammer-vlsi/hammer_vlsi/hammer_tool.py
src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py
src/test/unittests.sh

Add input/output delay constraint API

---

.gitmodules

Remove unused barstools

---

src/hammer-tech/hammer_tech.py
src/hammer-tech/schema.json
src/hammer-tech/stackup.py
src/hammer-vlsi/defaults.yml
src/hammer-vlsi/hammer_vlsi/hammer_tool.py
src/hammer-vlsi/tech_test.py

This adds basic fields for the stackup info (width, spacing, index, etc.) and a method for getting info.

Add support for stackups in the tech json

---

src/hammer-vlsi/common/mentor/defaults.yml
src/hammer-vlsi/defaults.yml
src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py

https://github.com/ucb-bar/hammer-cad-plugins/issues/41 in order to make https://github.com/ucb-bar/hammer-cad-plugins/pull/40 work

Mentor home

---

src/hammer-vlsi/defaults.yml

Update documentation to match current situation.
No functional change.

Power strap generation is supported now

---

src/hammer-vlsi/defaults.yml
src/hammer-vlsi/generate_properties.py
src/hammer-vlsi/hammer_vlsi/cli_driver.py
src/hammer-vlsi/hammer_vlsi/constraints.py
src/hammer-vlsi/hammer_vlsi/driver.py
src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py
src/hammer-vlsi/sram_generator/mocksram_generator.py
src/hammer-vlsi/sram_generator/nop.py
src/hammer-vlsi/test.py

Ready for code review.
Works when consuming IR from https://github.com/ucb-bar/barstools/pull/50
See tech specific repo for an implmentation.

Working draft of SRAMCompiler

---

src/hammer-vlsi/defaults.yml

Add simple clock gating api

---

src/hammer-vlsi/defaults.yml

This is causing me issues downstream as predicted by Edward
Fixes #359

Expand bump defaults

---

src/hammer-vlsi/defaults.yml
src/hammer-vlsi/hammer_vlsi/constraints.py
src/hammer-vlsi/hammer_vlsi/hammer_tool.py
src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py
src/hammer-vlsi/par/mockpar/__init__.py
src/hammer-vlsi/par/mockpar/defaults.yml
src/hammer-vlsi/par/nop.py
src/hammer-vlsi/tech_test.py
src/hammer-vlsi/test.py
src/test/mypy.sh

**Metadata: rebase merge**
This PR will

Move power straps APIs into core hammer, fixes #73

---

src/hammer-vlsi/defaults.yml

Fix documentation issues in defaults.yml, fixes #381

---

src/hammer-vlsi/defaults.yml

Reference vlsi.inputs.supplies in power_spec_mode

---

src/hammer-vlsi/defaults.yml
src/hammer-vlsi/hammer_vlsi/constraints.py

Add GDS and netlist to the hierarchical submodule struct

---

src/hammer-vlsi/defaults.yml
src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py
src/hammer-vlsi/test.py

Add punch-through sdc API

---

src/hammer-vlsi/defaults.yml
src/hammer-vlsi/hammer_vlsi/constraints.py
src/hammer-vlsi/hammer_vlsi/hammer_tool.py

Add `custom_cell` field in BumpAssignment constraint to override the default bump for any given bump.
For https://github.com/ucb-bar/hammer-cad-plugins/pull/107

Enhance bump API

---

src/hammer-vlsi/defaults.yml

Document Python type of clock constraints

---

src/hammer-vlsi/defaults.yml
src/hammer-vlsi/generate_properties.py
src/hammer-vlsi/hammer_vlsi/driver.py
src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py

Needed for https://github.com/ucb-bar/hammer-cad-plugins/pull/109

Add input ILMs to the LVS interface to allow hierarchical LVS

---

src/hammer-vlsi/defaults.yml

No functional change.
It isn't overridable per layer but is overridable in general

Remove confusing statement

---

src/hammer-vlsi/constraints_test.py
src/hammer-vlsi/defaults.yml
src/hammer-vlsi/hammer_vlsi/constraints.py
src/hammer-vlsi/hammer_vlsi/hammer_tool.py
src/hammer-vlsi/test.py

**Metadata: rebase-merge**
Companion PR forthcoming.

Implement semi-auto pin placement API

---

src/hammer-vlsi/defaults.yml

Add an example of how to use master

---

src/hammer-tech/hammer_tech.py
src/hammer-tech/schema.json
src/hammer-vlsi/constraints_test.py
src/hammer-vlsi/defaults.yml
src/hammer-vlsi/generate_properties.py
src/hammer-vlsi/hammer_vlsi/cli_driver.py
src/hammer-vlsi/hammer_vlsi/constraints.py
src/hammer-vlsi/hammer_vlsi/driver.py
src/hammer-vlsi/hammer_vlsi/hammer_tool.py
src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py
src/hammer-vlsi/pcb/generic/__init__.py
src/hammer-vlsi/pcb/generic/defaults.yml
src/hammer-vlsi/test.py
src/test/mypy.sh

**Metadata: rebase merge**
This PR will add a `HammerPCBDeliverableTool` and an implementation to create an open version of footprints and schematic symbols

Add PCB deliverables, fixes #122 and #364

---

src/hammer-tech/hammer_tech.py
src/hammer-tech/schema.json
src/hammer-vlsi/defaults.yml
src/hammer-vlsi/hammer_vlsi/hammer_tool.py
src/hammer-vlsi/tech_test.py

To be used when creating an LVS netlist

Add physical only cell list API

---

src/hammer_config/config_src.py

Also accept yaml as filename

---

src/hammer-vlsi/cli_driver_test.py
src/hammer-vlsi/defaults.yml
src/hammer-vlsi/hammer_vlsi/constraints.py

Add a 'create' field to PlacementConstraint that will allow the PNR tool to create instances that are not in the source netlist (e.g. physical-only cells)

Add a create field

---

src/hammer-vlsi/hammer_vlsi/hammer_tool.py

Add an option to allow user to use hammer_tool.*append with nice python indentation and remove it in the output code.

Indentation helper switch

---

src/hammer-vlsi/constraints_test.py
src/hammer-vlsi/defaults.yml
src/hammer-vlsi/hammer_utils/__init__.py
src/hammer-vlsi/hammer_vlsi/constraints.py
src/hammer-vlsi/hammer_vlsi/driver.py
src/hammer-vlsi/pcb/generic/__init__.py
src/hammer-vlsi/test.py
src/hammer-vlsi/utils_test.py

Also makes a few code structure changes to be less repetitive

Add an additional PCB deliverable that we need for our PCB flow

---

src/hammer-vlsi/defaults.yml
src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py

Add a field to specify specific checks to run (blank = all)

Select DRC checks

---

src/hammer-vlsi/cli_driver_test.py
src/hammer-vlsi/defaults.yml
src/hammer-vlsi/hammer_vlsi/cli_driver.py
src/hammer-vlsi/hammer_vlsi/driver.py
src/hammer-vlsi/hammer_vlsi/hammer_build_systems.py
src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py
src/hammer-vlsi/test.py

This is still very beta, but it seems to work.

First pass at a Makefile generator, fixes #234 and #453

---

src/hammer-vlsi/hammer_vlsi/cli_driver.py
src/hammer-vlsi/hammer_vlsi/driver.py
src/hammer_config/config_src.py
src/hammer_config_test/test.py

**Metadata: rebase merge**
This will aim to fix #71, #270, ~and #276~. I'm going to try to fix them individually so let's rebase merge this.

Make relative paths work in various places

---

src/hammer-vlsi/constraints_test.py
src/hammer-vlsi/defaults.yml
src/hammer-vlsi/hammer_vlsi/constraints.py
src/hammer-vlsi/hammer_vlsi/hammer_tool.py
src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py

Add basic support for clock groups

---

src/hammer-vlsi/technology/asap7/asap7.tech.json
src/hammer-vlsi/technology/asap7/defaults.yml

Support through PAR including stackup, core site, and extraction files added to ASAP7 plugin.

asap7 works through par

---

doc/CAD-Tools/Hammer-CAD-Tools.rst
doc/Hammer-Flow/DRC.rst
doc/Hammer-Flow/LVS.rst
doc/Hammer-Flow/PAR.rst
doc/Hammer-Intro.rst
doc/Hammer-Use/Buildfile.rst
doc/Hammer-Use/Hammer-APIs.rst
doc/Hammer-Use/Hooks.rst
doc/Hammer-Use/index.rst
doc/Technology/Tech-defaults.rst
doc/Technology/Tech-json.rst

Working in parallel with @dpgrubb13.

Update many docs

---

src/hammer-vlsi/generate_properties.py
src/hammer-vlsi/hammer_vlsi/driver.py
src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py
src/hammer-vlsi/par/mockpar/__init__.py
src/hammer-vlsi/par/nop.py

Fixes for post PAR simulation.

Post par sim

---

doc/CAD-Tools/Hammer-CAD-Tools.rst
doc/Hammer-Basics/Hammer-Overview.rst
doc/Hammer-Flow/Hammer-Actions.rst
doc/Hammer-Use/Buildfile.rst
doc/Hammer-Use/Flow-Control.rst
doc/Hammer-Use/Hooks.rst
doc/Hammer-Use/index.rst
doc/Technology/Tech-json.rst
doc/Technology/index.rst
src/hammer-tech/hammer_tech.py
src/hammer-vlsi/hammer_vlsi/cli_driver.py
src/hammer-vlsi/hammer_vlsi/hammer_build_systems.py
src/hammer-vlsi/hammer_vlsi/hammer_tool.py
src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py
src/hammer-vlsi/hammer_vlsi/hooks.py
src/hammer-vlsi/technology/asap7/__init__.py
src/hammer-vlsi/test.py

This PR fixes multiple issues:
* Closes #310 by implementing `--after_step` and `--until_step` command line arguments. These exclude the specified steps, with appropriate legalization checks.
* Closes #311 by implementing the ability for the tech plugin subclasses to implement a `get_tech_<action>_hooks` so that it can add hooks and the tool plugin to also implement hooks. The priority is implemented also.
* Closes #430 by implementing a concept of "persistent" hooks. Persistent = always run at beginning, pre_persistent = always run at beginning unless first step to run is after the target step, post_persistent = always run at beginning if target step is before the first step to run.
* Closes #87 (I believe) by being able to insert hooks w.r.t. any step.
* Closes #335 (documentation)
* …

Updates to step infrastructure

---

README.md
doc/Hammer-Basics/Hammer-Overview.rst

Update docs to clarify how to get plugin access

---

src/hammer-vlsi/generate_properties.py
src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py
src/test/mypy.sh
src/test/mypy_with_exclusions.sh

* Update pointers to tool plugins to check them if they exist.
* Optionally pass an argument to `mypy_with_exclusions.sh` with the technology name so that mypy can also check the tech plugin.
* Fix all_regs type.

Type check plugins

---

src/hammer-vlsi/defaults.yml

Small typo

---

.gitignore
doc/Examples/index.rst
doc/Examples/openroad-nangate45.rst
doc/index.rst
src/hammer-vlsi/common/openroad/defaults.yml
src/hammer-vlsi/defaults.yml
src/hammer-vlsi/drc/openroad/__init__.py
src/hammer-vlsi/drc/openroad/defaults.yml
src/hammer-vlsi/hammer_vlsi/vendor/__init__.py
src/hammer-vlsi/hammer_vlsi/vendor/openroad.py
src/hammer-vlsi/par/openroad/__init__.py
src/hammer-vlsi/par/openroad/defaults.yml
src/hammer-vlsi/synthesis/yosys/__init__.py
src/hammer-vlsi/synthesis/yosys/defaults.yml
src/hammer-vlsi/technology/nangate45/README.md
src/hammer-vlsi/technology/nangate45/__init__.py
src/hammer-vlsi/technology/nangate45/defaults.yml
src/hammer-vlsi/technology/nangate45/nangate45.tech.json
src/hammer-vlsi/technology/nangate45/sram-cache.json
src/hammer-vlsi/technology/nangate45/sram_compiler/__init__.py

__overview__
- this assumes a pristine OpenROAD-flow installation somewhere on the machine. no hacks to OpenROAD-flow used 
- the default OpenROAD-flow tcl-scripts are used to drive the tools. hammer just sets up run directories/configs
- documentation not complete, and several TODOs in the code
- ran on personal laptop running Ubuntu 18
__results__
- default RocketConfig makes it through __non-hierarchical__ srams,synthesis,par,drc
- all def/gds outputs look reasonable after each steppnr
- quality issues with drc and PPA reports after routing
- no simulation possible since no stdcell behavioral models exist
- no lvs possible since no stdcell spice/cdl exists
- syn+pnr take ~4 hours, drc might not finish

OpenROAD complete backend with nangate45

---

src/hammer-vlsi/hammer_vlsi/submit_command.py

Tested that this works for me when I ctrl+c during a tool run

Save and restore terminal settings around commands Fixes #69

---

src/hammer-vlsi/technology/asap7/sram_compiler/memories/behavioral/sram_behav_models.v

Fix 512x64 SRAM model

---

src/hammer-vlsi/hammer_vlsi/hammer_tool.py

Fix orientation markers for PCB visualizations

---

src/hammer_config/config_src.py

This enables nested keys to have their values transcluded

Add the transclude action to deepsubst meta action

---

doc/Hammer-Use/Hierarchical.rst

First draft of documentation for hierarchical flow needed for 290C tapeout class.
The limitations at the bottom may need to be checked more thoroughly.

Hierarchical flow docs

---

src/hammer-vlsi/cli_driver_test.py

Bridge targets added to Makefile but unit test was not updated.

Fix unittest caused by #631

---

doc/Hammer-Flow/Formal.rst
doc/Hammer-Flow/index.rst
src/hammer-tech/hammer_tech.py
src/hammer-vlsi/cli_driver_test.py
src/hammer-vlsi/defaults.yml
src/hammer-vlsi/generate_properties.py
src/hammer-vlsi/hammer_vlsi/cli_driver.py
src/hammer-vlsi/hammer_vlsi/driver.py
src/hammer-vlsi/hammer_vlsi/hammer_build_systems.py
src/hammer-vlsi/hammer_vlsi/hammer_tool.py
src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py
src/test/mypy.sh

Adds a "formal" action (closes #329). At first, only logical equivalence checking is implemented, though many other formal verification checks can be added as the need arises.

Formal Verification (LEC at first)

---

src/hammer-vlsi/technology/asap7/sram_compiler/__init__.py

Add specify block in SRAM compiler for vcs sdf back-annotation.

Add specify block in SRAM compiler for vcs sdf back-annotation

---

hammer/vlsi/hammer_tool.py

Catch a minor problem where offset in visualization is not properly shown.

Fix visualization to include a global offset if it exists.

---

hammer/config/defaults.yml
hammer/config/defaults_types.yml

Adds simple key interface for basic retiming to be implemented in the tool plugins.

add retiming key

---

hammer/par/innovus/__init__.py

- [X ] Bug fix
**Impact**:
- [X ] Change to a Hammer plugin

Hotfix for write_stream

---

doc/Hammer-Basics/Migration-Guide.md
doc/Hammer-Use/Buildfile.rst
doc/Hammer-Use/Hammer-Config.rst
doc/Hammer-Use/Hooks.rst
e2e/configs/mock_hier.yml
hammer/config/config_src.py
hammer/config/defaults.yml
hammer/config/defaults_types.yml
hammer/generate_properties.py
hammer/lvs/icv/__init__.py
hammer/lvs/mocklvs/__init__.py
hammer/lvs/netgen/__init__.py
hammer/par/innovus/__init__.py
hammer/par/mockpar/__init__.py
hammer/par/openroad/__init__.py
hammer/synthesis/genus/__init__.py
hammer/tech/stackup.py
hammer/technology/asap7/__init__.py
hammer/technology/asap7/defaults.yml
hammer/technology/sky130/__init__.py
hammer/technology/sky130/defaults.yml
hammer/vlsi/driver.py
hammer/vlsi/hammer_tool.py
hammer/vlsi/hammer_vlsi_impl.py
tests/test_config.py
tests/test_power_straps.py

Miscellaneous fixes/features post-Q2 tapeout, including:
- Fix ILMs not fully propagating (full hierarchical tree for LVS, see description below)
- Fix macro pin promotion
- Fix routing obstruction type also including PG obstruction
- Add top/bottom routing layer key (due to Innovus command deprecation) & fix some Genus command deprecations
- Use the tapcells list for power rail reference
- Add `prepend` meta directives similar to the append ones. Needed for certain lists where order matters (e.g. include directories)
Details about the LVS ILM fix:
- `vlsi.inputs.ilms` is now propagated through the flow so that each par node appends to it. Thus for any level in the hierarchical tree, it contains the full dependency tree
- `par.outputs.output_ilms` continues to only contain the children …

Post Q2 Tapeout Fixes

---

hammer/synthesis/genus/__init__.py

Make genus report unconstrained paths

---

hammer/par/innovus/__init__.py

set_dont_use must be in ILM-flattened mode, which can only be after reading the ILMs in floorplan_design
**Impact**:

Innovus move set_dont_use to after floorplan_design

---

hammer/par/innovus/__init__.py

Name obstruction constraints in the Innovus db

---

hammer/par/innovus/__init__.py

Name the bump blockages

---

hammer/lvs/pegasus/__init__.py
hammer/technology/sky130/__init__.py
hammer/technology/sky130/sky130.tech.json
hammer/technology/sky130/sram_compiler/__init__.py

- Update to follow file structure of latest Cadence SKY 130 PDK release
- Add support for blackboxing SKY 130 SRAMs in Pegasus 
**Impact**:

Update plugin for Cadence's latest SKY 130 PDK release

---

hammer/common/cadence/__init__.py
hammer/config/defaults.yml
hammer/config/defaults_types.yml
hammer/par/innovus/__init__.py
hammer/par/openroad/__init__.py

Note: clock tree creation can happen if custom files specified but no `vlsi.inputs.clocks`. I think this is a sufficient use case.
**Impact**:

Add key for custom SDC files
