src/addons/synthesis/dc/tools/run-synthesis

At the end of synthesis, dc tries to open a GUI that I don't have a license
for. Unsetting DISPLAY stops this from happening.

unset DISPLAY in dc run-synthesis

---

.gitmodules

Makes the modular hammer hard to clone/use

Remove rocketchip module

---

src/hammer-vlsi/hammer_vlsi.py

Now we don't need $PWD and $(readlink -f) when calling hammer-vlsi from the CLI
Templates to be updated as well.
@colinschmidt

Don't assume current working directory is hammer-vlsi

---

.gitignore

This makes git status clean if you set `--obj-dir $PWD`

add gitignore for using hammer dir as obj-dir

---

src/hammer-vlsi/hammer_vlsi.py

Did this a while ago but forgot to PR it.
I'm not sure if the strings are tech or tool specific so if we figure that out we might want a config that maps between independent versions and the specific ones.

add orientation support to floorplan json

---

src/hammer-vlsi/README.md
src/hammer-vlsi/hammer_vlsi.py
src/hammer-vlsi/par/nop.py
src/hammer-vlsi/synthesis/mocksynth/__init__.py

In preparation for hierarchical which may perform multiple invocations
of the same tool in the same process, and we want to avoid the risk of
variables not being reset between runs.

Revamp load_tool to take the class object instead of an instance

---

src/hammer-tech/hammer_tech.py
src/hammer-vlsi/hammer_vlsi_impl.py

Due to a Python bug/missing feature. This causes `import hammer_vlsi` to fail which is a fatal error for trying to use hammer.
Until python/cpython#7950 is merged (and Python 3.8 becomes widespread) we'll have to avoid nested Enum classes.
Sorry @colinschmidt  :-(

No nested enum

---

src/hammer-vlsi/synthesis/vivado/file_templates/paths.tcl

This makes it OK to have multiple verilog sources.

Adding quotes to the path.tcl template.

---

.gitignore
src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py

Currently the parent classes of SynopsysTool and CadenceTool have empty sets for env_vars, but these could squash the env_vars of other traits in multiply-inherited subclasses.

Call super().env_vars in *Tool

---

src/hammer-vlsi/defaults.yml
src/hammer-vlsi/hammer_vlsi/__init__.py
src/hammer-vlsi/hammer_vlsi/driver.py
src/hammer-vlsi/hammer_vlsi/hammer_submit_command.py
src/hammer-vlsi/hammer_vlsi/hammer_tool.py
src/hammer-vlsi/hammer_vlsi/submit_command.py
src/hammer-vlsi/test.py
src/hammer_config/config_src.py
src/test/mock_bsub.sh

This PR moves most of the guts of HammerTool.run_executable into a new class HammerBareSubmitCommand, a subclass of a new abstract HammerSubmitCommand (not sold on this name) that would allow us to implement LSF, qsub, etc. An example LSF command is included but it needs some features.

First pass implementation of submission commands

---

src/hammer_config/config_src.py
src/hammer_config_test/test.py

Main highlights: enable a setting with dynamic meta directives to reference another setting with dynamic meta directives. Enables dynamic meta directives to reference themselves (enables things like dynamicappend, etc). General refactors to make dealing with meta directives more DRY.
Paves the way to fixing #230.
This PR should be fully backwards-compatible (only introduces new support, doesn't remove any features).

Refactor hammer_config

---

src/hammer-vlsi/generate_properties.py
src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py
src/test/check_generate_properties.sh

Closes #237 
This is reliant on #213. Running `./generate_properties.py` now directly edits `hammer_vlsi_impl.py`.

Auto generate properties

---

src/hammer-tech/hammer_tech.py

This is a bugfix after recent changes caused this filter to run on all lib reading.
It would have been better to check the corners for matching libraries but hammer-tech doesn't parse MMMCCorners yet. I've left a TODO for fixing that.

supply filter assumes mmmc runs need all libraries

---

src/hammer-vlsi/hammer_vlsi/submit_command.py
src/hammer-vlsi/test.py
src/test/mock_bsub.sh

Some tools won't produce output to their own log
or won't produce output until after the tool may fail
this makes sure we have something to show for our time

Always log stdout and stderr of lsf to file

---

.gitignore
src/hammer-tech/hammer_tech.py
src/hammer-vlsi/hammer_vlsi/driver.py
src/hammer-vlsi/hammer_vlsi/hammer_tool.py
src/hammer_config/config_src.py

This makes it return slightly saner Nones instead of string "null"s. No current calls to get_setting use "null" so this seems safe.
It's also worth noting that you may want a null value that is not type `Optional[str]` (and in fact we do this in the calibre plugin).
@harrisonliew does this solve your issue on ucb-bar/hammer-cad-plugins#40 ?

Change get_setting to use None as a default nullvalue

---

src/hammer_config/config_src.py
src/hammer_config_test/test.py

Should now work correctly on arrays
Close #334

Fix subst target identification

---

src/hammer-vlsi/defaults.yml
src/hammer-vlsi/generate_properties.py
src/hammer-vlsi/hammer_vlsi/constraints.py
src/hammer-vlsi/hammer_vlsi/driver.py
src/hammer-vlsi/hammer_vlsi/hammer_tool.py
src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py
src/hammer-vlsi/par/nop.py
src/hammer-vlsi/test.py
src/hammer-vlsi/vivado_core.py

Metadata: rebase and merge
Add the ability to generate a CPF power spec.
This also includes a simple supply net API to enable the CPF generation.
This only supports single domain power specifications for now.
I also threw in a free refactor (for that negative line count despite adding a feature achievement) 
I tested this on a downstream template, it works as before not breaking SYN, PAR, or LVS.

Add supply and cpf api

---

src/hammer-vlsi/defaults.yml
src/hammer-vlsi/hammer_vlsi/constraints.py
src/hammer-vlsi/hammer_vlsi/hammer_tool.py
src/hammer-vlsi/test.py

This is a new optional API that allows the user to specify
a rectangular set of bumps and assign them to signals,
power/ground, leave them unconnected, or remove them.

Add an API for placing and assigning bumps

---

src/hammer-tech/stackup.py
src/hammer-vlsi/cli_driver_test.py
src/hammer-vlsi/defaults.yml
src/hammer-vlsi/hammer_vlsi/constraints.py

This upstreams something I always end up adding in hooks. A lot of hardmacros will need keep-outs around them because their pins cannot handle power grids or standard cells directly adjacent.
This API is intended to be used to implement these keep-outs. The top-layer is optional and no keep-out should be created if it is not specified if it is specified the keep-out will be up and including the layer specified in the key.

Top layer placement api

---

src/hammer-vlsi/defaults.yml
src/hammer-vlsi/hammer_vlsi/constraints.py
src/hammer-vlsi/hammer_vlsi/hammer_tool.py
src/hammer-vlsi/tech_test.py
src/hammer-vlsi/tech_test_utils.py
src/hammer-vlsi/test.py
src/hammer-vlsi/test_tool_utils.py

Fixes #112 and ucb-bar/hammer-cad-plugins#52
Relatively simple but enables user to have a decent amount of control.
The user can select pins and which layers/side they are placed on.
In addition pins associated with macros that should not be placed
can also be handled
There is a unit test and I also ran it on my favorite technology.

Add pin assignment API

---

src/hammer-vlsi/hammer_vlsi/cli_driver.py

This lets the user investigate the current hierarchical settings
when generating extra hooks

add driver as input to get_extra_hierarchical_*_hooks

---

src/hammer-tech/hammer_tech.py
src/hammer-tech/schema.json
src/hammer-tech/stackup.py
src/hammer-vlsi/defaults.yml
src/hammer-vlsi/hammer_utils/__init__.py
src/hammer-vlsi/hammer_vlsi/hammer_tool.py
src/hammer-vlsi/tech_test.py
src/hammer-vlsi/test_tool_utils.py
src/hammer-vlsi/utils_test.py

Fixes #319. This adds site objects which will be used for hierarchical floorplanning checks in ucb-bar/hammer-cad-plugins#91
This will also finally switch the coordinate system over to integer multiples of the manufacturing grid instead of dealing with floats and rounding everywhere.

Add Site objects and use Decimal for Site and Stackup

---

src/hammer-vlsi/defaults.yml

No functional change. `std_cell_rail_layer` is actually the correct key

Fix typo and tweak type descriptions

---

src/hammer-tech/stackup.py
src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py

We ran into issues with a malformed tech plugin that silently generated nonsensical power straps. Also funnily enough, our place and route tool of choice does NOT error out when you specify a negative power strap width...

Add some assertions to sanity check the tech plugin

---

src/hammer-vlsi/defaults.yml
src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py

Issue: https://github.com/ucb-bar/hammer/issues/357
Replaced 'blank' with 'empty'.

Power straps mode change

---

src/hammer-vlsi/hammer_utils/__init__.py
src/hammer-vlsi/utils_test.py

This fixes a crash that can happen if `check_function_type` is used on an untyped argument. It has no functional change to the code at large.

Don't crash on checking untyped arguments

---

src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py
src/hammer-vlsi/par/mockpar/__init__.py
src/hammer-vlsi/par/nop.py

This fixes power strap issues we ran into at the top level by passing blockage_spacing to the method that builds std cell rails.

Add blockage_spacing to standard cell power strap placement

---

src/hammer-tech/hammer_tech.py
src/hammer-vlsi/cli_driver_test.py
src/hammer-vlsi/constraints_test.py
src/hammer-vlsi/defaults.yml
src/hammer-vlsi/hammer_utils/__init__.py
src/hammer-vlsi/hammer_utils/lef_utils.py
src/hammer-vlsi/hammer_vlsi/constraints.py
src/hammer-vlsi/hammer_vlsi/driver.py
src/hammer-vlsi/hammer_vlsi/hammer_tool.py
src/hammer-vlsi/lef_utils_test.py
src/hammer-vlsi/tech_test.py
src/hammer-vlsi/test.py
src/hammer-vlsi/utils_test.py
src/hammer_config/config_src.py

Switch margins and constraints over to Decimal and make width/height for hard macros optional.

Floorplan Constraints Overhaul. Fixes #113 and #376

---

src/hammer-tech/hammer_tech.py
src/hammer-vlsi/cli_driver_test.py
src/hammer-vlsi/hammer_vlsi/cli_driver.py
src/hammer-vlsi/par/mockpar/__init__.py
src/hammer-vlsi/tech_test.py
src/hammer-vlsi/test.py
src/hammer-vlsi/test_tool_utils.py
src/hammer_config/config_src.py
src/hammer_config/yaml2json.py

One of the CLI driver `json.dumps` needed the special Hammer serializer to work with Decimals. I think we should get rid of this when we solve #378 by not serializing `Decimal`s directly.

Fix JSON serialization bug with Decimals

---

src/hammer-vlsi/pcb/generic/__init__.py

When merging the tech plugin after #420, I realized that I didn't scale the pitch in the PCB footprint.

PCB bump pitch should use post-shrink units

---

src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py

Proposed in ucb-bar/hammer-cad-plugins#116, this moves the `append` and `verbose_append` methods to a mixin trait that is then used by `CadenceTool` and could be used in the future by other tool types.

Add a TCLTool mixin

---

src/hammer-vlsi/defaults.yml
src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py
src/hammer-vlsi/test.py

This is needed to add an absolute offset to the power strap start position relative to the design's bounding box.
This is very useful to align power straps between blocks in hierarchical P&R.

Add absolute track_offset

---

src/hammer-vlsi/hammer_vlsi/cli_driver.py

Calling hammer with `-p ../../foo.yml` does not give the correct behavior when using the `prependlocal` meta or `local` deepsubst metas.

Canonicalize the input file paths

---

.travis.yml
src/hammer-tech/hammer_tech.py
src/hammer-vlsi/hammer_vlsi/cli_driver.py

This passes and replicates most of the build-bot (it should be able to support 3.3 and 3.4 but I don't know how the build-bot works around the typing issue).

Add travis support

---

src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py

- No need to `set_clock_groups` if there are none

Fix clock groups

---

src/hammer-tech/schema.json
src/hammer-tech/stackup.py

- `max_width` is an optional field which specifies the maximum wire width on that layer
- The power straps algorithms will not generate a wire width > `max_width`

Allow max_width option for layers

---

src/hammer-tech/hammer_tech.py

1. use python internal `tarfile` and `os.chmod` to get rid of external command.
2. `asap7` https://github.com/ucb-bar/hammer/pull/443 contains recursive tarball, this patch make `extract_tarballs` extract tarball recursively.

recursively extract and chmod

---

src/hammer-tech/hammer_tech.py
src/hammer-vlsi/technology/asap7/__init__.py

This PR requires #512.
Since https://github.com/ucb-bar/hammer/pull/511#issuecomment-530627815
This PR replace `python-gdsii` with `gdspy` for the manipulation to gds in `post_par_script` hook to solve the precision problem in the asap7.

replace python-gdsii with gdspy

---

src/hammer-tech/schema.json
src/hammer-tech/stackup.py
src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py
src/hammer-vlsi/tech_test.py

First attempt at fixing #497 & #502
Optional tech schema for quantized wire widths (LEF58_WIDTHTABLE)
- Checks desired strap width against provided table
- Quantizes down, except for highest value in table, for which all widths at least that one are allowed
- Issues logger warning if quantization happened (I don't like how I implemented this)
Simple check for strap density (sum of widths/pitch), warns if over 85%.

Power strap API checks density & against width table

---

src/hammer-vlsi/hammer_vlsi/cli_driver.py
src/hammer-vlsi/hammer_vlsi/driver.py
src/hammer_config/config_src.py
src/hammer_config_test/test.py

Please comment if you think there's a philosophical reason to keep this, otherwise it blocks some functionality because one cannot just `-p` another yml with small settings changes, e.g. when doing a `make redo-par` that takes the `par-output-full.json`.

fixes #476, json now equal with yml

---

src/hammer-tech/hammer_tech.py

Addresses a small issue that came up where tech cache was created despite an invalid tarball was specified, so it skipped the post-extraction hacking for ASAP7.

Check invalid tarballs

---

src/hammer-tech/hammer_tech.py

This is meant to make it so the tech plugin does not have to use the special cells API.  The special cells API is currently pretty simple and would typically be overridden by a hook, so I think it is better to allow the user to not define any special cells in the tech plugin if they plan on using a hook anyways.

make special cells return None if not defined in tech plugin

---

src/hammer-vlsi/hammer_vlsi/hammer_tool.py
src/hammer-vlsi/test.py

Minor quality of life typo: it printed out `Sub-step 'step' skipped due to pause hook` despite having actually run it when you specified a `--to_step`.

Bad logging when --to_step used

---

LICENSE
README.md

Hopefully this will allow github's auto-detection feature correctly
identify the 3-clause BSD license we use. Fixing #557
I made this change after comparing our license file to the text here: https://choosealicense.com/licenses/bsd-3-clause/
I'm not sure if we can test this on a branch or not. I'm also unsure how often the auto-detection is run.

Move nonstandard language out of license to readme.

---

src/hammer-tech/hammer_tech.py
src/hammer-vlsi/tech_test.py

Motivated by new use case after implementing ability to hack PDK tarballs (e.g. ASAP7).
This allows a tech plugin that accesses existing PDK installs to implement a `post_install_script` which could copy some file and hack it into the tech cache dir. Then, the tech JSON can point to this hacked file such as follows:
```
{
"installs": [
{
"path": "tech-asap7-cache",
"base var": ""
}
],
...
```
The `path` must be the basename of the tech cache directory. In most cases, it is `tech-<tech_name>-cache`. `base var` must be left as an empty string.

Add ability to hack installs into cache dir

---

src/hammer-vlsi/hammer_vlsi/hammer_tool.py

Follow up to #437 
Since the function used is cleandoc, I think it suffices to just refer to this function.

Add note to refer to cleandoc

---

src/hammer-vlsi/defaults.yml

Enables designs without floorplan information to still have blockage around macros.

Add generic top_layer setting for blockage spacing.

---

sourceme.sh

If no ${HAMMER_HOME} is specified, the script finds the location of itself (even if called through symlinks) and uses that as the the default.
Users who wish to set this manually can do so prior to invoking the script, as was the previous behaviour.

Make sourceme.sh set HAMMER_HOME to its root dir by default

---

src/hammer-tech/hammer_tech.py
src/hammer-vlsi/tech_test.py
src/hammer-vlsi/technology/nop/__init__.py
src/hammer-vlsi/test_tool_utils.py

I believe this code was only around to try to have a fallback in case the technology passed didn't have an `__init__.py` which I think isn't something we truly support.
This fix also allows for changes like #576 or any otherwise broken (via ImportError) tech plugins to be noticed rather than silently ignored.

Error if we can't load the specified technology

---

doc/Hammer-Flow/Simulation.rst
src/hammer-vlsi/defaults.yml

This PR is linked with https://github.com/ucb-bar/chipyard/pull/650.
It adds a new YAML input to pass in `LDFLAGS` into the VCS/C linker. It also renames the previous C compiler pass-in flag.

Add support for passing in LDFLAGS during simulation

---

src/hammer-vlsi/hammer_vlsi/cli_driver.py
src/hammer-vlsi/hammer_vlsi/driver.py
src/hammer-vlsi/hammer_vlsi/hammer_build_systems.py

Pass hier stuff to sim & power actions. 
TODO: tool plugin implementation will require some additional documentation/keys (e.g. benchmarks are only valid for top-level hierarchy).

Basic hierarchical support for sim & power

---

src/hammer-vlsi/defaults.yml
src/hammer-vlsi/hammer_vlsi/constraints.py
src/hammer-vlsi/hammer_vlsi/driver.py

This adds an optional `sim_netlist` field to the `ILMStruct`. If specified, this netlist is appended to a parent module's netlist for hierarchical simulation.
Used by ucb-bar/hammer-cadence-plugins/#64.

Hierarchical simulation netlists

---

src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py

Closes #608 and required for ucb-bar/hammer-synopsys-plugins#17

SynopsysTool inherits from TCLTool

---

doc/Hammer-Use/Buildfile.rst

HAMMER_REDO_ARGS was renamed to HAMMER_EXTRA_ARGS

Fix documentation of `HAMMER_REDO_ARGS`

---

src/hammer-vlsi/hammer_vlsi/cli_driver.py
src/hammer-vlsi/hammer_vlsi/hammer_tool.py

Closes #554 and #585:
- Replaced steps use the new name in flow control
- Removed steps no longer targetable in flow control
- Get flow control hooks for drc, lvs, sim, power actions
- `first_step` and `persistent_steps` properties, `run_persistent_steps` method
- Persistent hooks and pre-persistent hooks whose target is the first step will always run at the beginning. See ucb-bar/hammer-cadence-plugins#71 for an example of how this is used in both `do_pre_steps` and the `open_chip` script.
- No change needed to unit tests

Flow Control Fixes + Enhancements

---

doc/Hammer-Flow/Power.rst
doc/Hammer-Flow/Simulation.rst
src/hammer-tech/filters.py
src/hammer-vlsi/defaults.yml
src/hammer-vlsi/hammer_vlsi/driver.py

Minor fixes:
* Due to ucb-bar/hammer-cadence-plugins#72, mentions of "VCD" should instead be "waveforms" in documentation.
* Power grid libraries are directories, not files

VCD -> waveforms, PG libraries are not files

---

src/hammer_config/config_src.py

This should add in support for an arbitrary number of meta variables applied sequentially to the inner value. This has been shown to have no change with single meta variables, and to function with `"local"` and `"transclude"`. While `"cwd"` has not been tested, it looks like it _should_ work. This circumvents the issue where a list of meta deepsubst variables would cause Hammer to fail.

Deepsubst multiple meta variables support

---

src/hammer-vlsi/hammer_vlsi/driver.py
src/hammer_config/__init__.py

We add the special key for tracking relative directories to each dictionary that contains a `vlsi.inputs.hierarchical.constraints`.
This allows any future use of this dictionary to be able to resolve `prependlocal` meta actions or any future path relative meta actions.
We avoid adding this path variable if it already exists in the case that this procedure has already occured. Overwriting the path in that case would cause us to update it and then potentially disconnect the relative path from its original directory.
This happens in the normal usage with syn-to-par step creating a new hammer_config file in a different level of the directory hierarchy.

Support relative directory meta application inside hierarchical constraints

---

src/hammer-vlsi/defaults_types.yml
src/hammer-vlsi/hammer_vlsi/hammer_vlsi_impl.py
src/hammer-vlsi/technology/asap7/sram_compiler/__init__.py
src/hammer-vlsi/test.py
src/hammer_config/config_src.py
src/hammer_config_test/test.py

The actual `hammer-vlsi` tool is now integrated with type-checking. Some minor changes to the types file and the addition of a flag that can be used to ignore type checking altogether.

Integrate type checking into tool

---

src/hammer-vlsi/defaults.yml
src/hammer-vlsi/defaults_types.yml

Changed default type of vlsi.core.node to int from str since in all the technology files `defaults.yml` the value is an int. Without this change the following error arises `Expected primary type str for vlsi.core.node, got type int`

Update defaults_types.yml to fix type error for vlsi.core.node

---

src/hammer-vlsi/defaults.yml

`vlsi.core.technology` is a str and `vlsi.core.node` is an int

Fix small error in tech defaults

---

doc/Hammer-Basics/Hammer-Setup.rst
doc/Hammer-Use/Hammer-Config.rst
src/hammer-vlsi/cli_driver_test.py
src/hammer-vlsi/hammer_vlsi/cli_driver.py
src/hammer-vlsi/synthesis/yosys/__init__.py
src/hammer-vlsi/tech_test.py
src/hammer_config/config_src.py

Every run of the CLI now creates a `{action}-output-history.yml` file that contains a flattened version of the full output config, annotated with comments describing the files that modified said keys in the order they were provided as project files in the CLI call. This is done by creating a temporary file similar in fashion to the CLI driver tests.
The feature requires the package [`ruamel.yaml`](https://pypi.org/project/ruamel.yaml/) since the `pyyaml` package does not support reading and writing comments in YAML.

Key history

---

src/hammer-vlsi/constraints_test.py
src/hammer-vlsi/defaults.yml
src/hammer-vlsi/hammer_vlsi/constraints.py
src/hammer-vlsi/hammer_vlsi/hammer_tool.py

Overlap should be used for certain type of cells. In LEFs, these should be of class COVER or of class MACRO with OVERLAP shapes inside.
This is particularly useful to prevent any P&R implementations from creating halo/blockage objects around the boundaries of these macros.

Add Overlap placement constraint type

---

hammer/config/config_src.py
hammer/vlsi/hammer_tool.py
tests/test_config.py

A quick PR to merge a simple utility method `get_settings_from_dict` originating from Xcelium PR. Goal is to simplify/standardize the process of getting multiple keys (often specified as a list of keys on which to perform `get_setting`) at once and returning a unified dictionary. Currently, such functionality is handled in multiple slightly different ways across the plugins.
Accompanied now by a unit test.

Utility Function v2

---

.github/workflows/publish.yml
pyproject.toml

This workflow will publish hammer to PyPI when a release is created on Github. The version number used in the tag of the release will be used as the version for the hammer-vlsi package. The PYPI_TOKEN used is mine, but once the package is published, I will add everyone else as admins on PyPI for hammer-vlsi.
Workflow based on this: https://nadeauinnovations.com/post/2020/08/one-version-to-rule-them-all-keeping-your-python-package-version-number-in-sync-with-git-and-poetry/

Workflow to Publish Hammer on Release

---

.github/workflows/pr.yml

Caches the venv generated by poetry install as long as the OS, python version, and poetry.lock files stay the same. Should reduce CI runtime to under 1 minute.
Based on: https://github.com/snok/install-poetry#testing

Cache Poetry venv in CI

---

hammer/config/config_src.py
hammer/config/defaults.yml
hammer/config/defaults_types.yml
hammer/pcb/generic/__init__.py
hammer/tech/__init__.py
hammer/vlsi/constraints.py
hammer/vlsi/hammer_tool.py
hammer/vlsi/hammer_vlsi_impl.py
tests/test_constraints.py
tests/test_tool.py

Bumps previously assume same x, y pitch.  This updates bumps such that:
- Dimensions are now acceptable arguments for pitch key (i.e., `vlsi.inputs.bumps.pitch`, `vlsi.inputs.bumps.pitch_x`, `vlsi.inputs.bumps.pitch_y` are now **all** acceptable).
- Global bump offset is available for unaligned bumps (e.g., `vlsi.inputs.bumps.global_x_offset`)
- Corresponding backend tool updates.
- Fixed PCB tool to adopt this scheme.
- Fixed visualization to deal with pitch.
See: https://github.com/ucb-bar/hammer-cadence-plugins/pull/87

Bump Update

---

hammer/config/config_src.py
hammer/vlsi/cli_driver.py

This employs the use of the HAMMER logger for warnings in both the config type warnings and the info action. It also fixes the type hinting and indentation of YAML dumped by ruamel.yaml.

use HAMMER logger, fix ruamel indents

---

hammer/config/defaults.yml
hammer/config/defaults_types.yml
hammer/tech/__init__.py
tests/test_tool.py

- Introduce a new method `get_timing_lib_with_preference` to allow users to select their timing lib of choice when multiple are available. This defaults to NLDM -> ECSM -> CCS. 
- New key `vlsi.technology.timing_lib_pref`.
- Backing unit test.
Note that the prior `get_timing_lib_with_ecsm_filter` is unaltered as it is used in yosys and sky plugins.
Cadence Changes here: https://github.com/ucb-bar/hammer-cadence-plugins/pull/88

New Method For Getting Timing Libs

---

.gitignore
doc/Technology/Tech-json.rst
e2e/configs/sky130-test.yml
e2e/pdks/asap7-a.yml
e2e/pdks/asap7-bwrc.yml
e2e/pdks/sky130-bwrc.yml
hammer/par/openroad/__init__.py
hammer/par/openroad/defaults_types.yml
hammer/tech/__init__.py
hammer/technology/sky130/__init__.py
hammer/technology/sky130/defaults.yml
hammer/vlsi/hammer_vlsi_impl.py

Small fixes for Chipyard compatibility:
- `cache` directory parsing in tech JSON
- vendor defaults need to be added to the config database
- bump some things in the e2e flow
- sky130 + openroad fixes
TODO:

Chipyard compatibility

---

hammer/config/defaults.yml
hammer/config/defaults_types.yml
hammer/vlsi/hammer_vlsi_impl.py

This PR adds power strap validity checking and power strap dumping for hardmacros as requested by rahulk29/substrate#92 and could eventually be extended for hierarchical design by abutment.
A new key, `par.power_straps_abutment` controls the checks. If `true`, straps are checked for abutment. This means that all instances of a given macro must be placed on a multiple of its top layer's power strap pitch, or else an error is thrown. If `false`, the layer above the macro's top layer must exist. In both situations, power obstructions on the relevant layer are checked for any overlaps.
Here is a test case: 
<details>
<summary>Input placement constraints</summary>
```
vlsi.inputs.placement_constraints:
- path: "pass"
type: toplevel
x: 0
y: 0
width: 100
height: 100
margins:
left: 0
right: 0 …
```

Check + dump power straps abutting/over hardmacros

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/PULL_REQUEST_TEMPLATE.md

In light of the new discussions posting guidelines, I have also generated issue & PR templates modeled off of the Chipyard ones.
You can see (mostly) what the issue templates look like by clicking on each yml file [here](https://github.com/ucb-bar/hammer/tree/issue_template/.github/ISSUE_TEMPLATE).

Issue & PR templates

---

.github/PULL_REQUEST_TEMPLATE.md
doc/CAD-Tools/OpenROAD.md
doc/CAD-Tools/OpenROAD.rst
doc/Technology/ASAP7.md
doc/Technology/ASAP7.rst
doc/Technology/Nangate45.md
doc/Technology/Nangate45.rst
doc/Technology/Sky130.md
doc/Technology/Sky130.rst

<-- Provide a brief description of the PR immediately below this comment, if the title is insufficient -->
Previously, I didn't include markdown pages correctly for readthedocs. Now, myst_parser is able to render it correctly. For example, see this difference:
Old: https://hammer-vlsi.readthedocs.io/en/latest/Technology/Sky130.html
New: https://hammer-vlsi.readthedocs.io/en/fix_myst/Technology/Sky130.html
Also fix the helper text in this PR template ^ (should not appear)
**Impact**:

Fix readthedocs pages for plugins

---

hammer/config/defaults.yml
hammer/config/defaults_types.yml

Exhaustively searched in plugins/Hammer core, only found these 2 keys to not be defined in defaults.
Closes #716
**Impact**:

Add missing keys to defaults

---

hammer/technology/sky130/extra/sky130-tech-gen-files/beginning.json
hammer/technology/sky130/extra/sky130-tech-gen-files/beginning_nda.json
hammer/technology/sky130/extra/sky130-tech-gen-files/cells.json
hammer/technology/sky130/extra/sky130-tech-gen-files/stackups-gen.py
hammer/technology/sky130/extra/sky130-tech-gen-files/stackups.json
hammer/technology/sky130/extra/sky130-tech-gen.py
hammer/technology/sky130/sky130.tech.json

Removed source.cdl file from sky130 plugin because it is unnecessary for LVS and throws an error during LVS when the NDA path is not valid.
Also updated the tech json generation python script to generate the updated sky130.tech.json.
Already tested in (chipyard) CI and rtl-to-gds flow works.
**Impact**:

Sky130 plugin fixes

---

pytest.ini

This PR adds a config file to eliminate the warning that `pytest.mark.long` is an unrecognized testing marker.
**Impact**:

add config to recognize marker

---

hammer/lvs/icv/__init__.py

Small fix to the config_runset key used in lvs flow.
**Impact**:

lvs config_runset key

---

hammer/config/defaults.yml
hammer/vlsi/hammer_vlsi_impl.py

Added UPF support to hammer. Generates a single power domain UPF. It should do exactly what hasCPFsupport does. Tested it by running PAR on the tapeout vlsi lab and manually feeding into innovus with the innovus command below:
read_power_intent -1801 power_spec.upf
[power_spec.pdf](https://github.com/ucb-bar/hammer/files/11116390/power_spec.pdf)
.
**Impact**:

Added UPF Support

---

hammer/config/defaults_types.yml

This PR fixes a default key type, and fixes LVS flows.
**Impact**:

fix lvs ILM type

---

hammer/drc/icv/__init__.py
hammer/lvs/icv/__init__.py

ICV errors due to providing the config_runset flag which does not exist. Instead it should be a runset_config flag.
Impacts only ICV and on DRC runs.
**Impact**:

Ivs config runset

---

hammer/drc/icv/__init__.py
hammer/lvs/icv/__init__.py

Users are manually changing the view_drc script to make it run from the generated-scritps directory. QoL improvement. 
**Impact**:

QoL to run view_drc within the generated-scripts

---

hammer/config/defaults_types.yml

This PR relaxes types for some constraints that have multiple value types.
**Impact**:

relax types

---

hammer/drc/klayout/__init__.py
hammer/drc/klayout/default_types.yml
hammer/drc/klayout/defaults.yml
hammer/par/openroad/__init__.py
hammer/power/joules/__init__.py
hammer/technology/sky130/__init__.py
hammer/technology/sky130/defaults.yml
hammer/technology/sky130/sky130.tech.json
hammer/vlsi/hammer_build_systems.py
hammer/vlsi/vendor/def2stream.py

KLayout is the preferred DRC checker for sky130 according to efabless.
This plugin generates the same DRC errors as Calibre for both gcd and the Chipyard TinyRocket Config, in an easy-to-understand GUI.
**Impact**:

KLayout DRC plugin

---

hammer/config/defaults.yml
hammer/vlsi/submit_command.py

Adding job submission via slurm (similar to LSF). 
This code was directly copied from edits made locally to the Hammer used for the EECS151 class.
The YAML config they used to run jobs via slurm was:
```
vlsi.submit.command: "slurm"
vlsi.submit.settings:
- slurm: {srun_binary: "/home/ff/eecs151/tools-151/scripts/srun151", extra_args: []}
```
**Impact**:

Slurm job submission option for EECS151

---

hammer/par/innovus/__init__.py

Move setting of routing layers to the end of the `init_design` Hammer step, to after tech LEFs are loaded.
closes #793
**Impact**:

Fix setting top/bottom routing layers in Innovus

---

hammer/common/cadence/__init__.py
hammer/config/defaults.yml
hammer/par/innovus/__init__.py
hammer/par/mockpar/__init__.py
hammer/vlsi/constraints.py

ILM SDCs were not getting read during parent synthesis. These SDCs predominantly have `set_case_analysis` and `set_annotated_transition` commands, which are required in some cases to properly choose the proper timing mode in lib files.
**Impact**:

Pass ILM SDCs upwards through hierarchical flow

---

doc/Technology/Tech-json.rst
hammer/config/defaults.yml
hammer/config/defaults_types.yml
hammer/par/innovus/__init__.py
hammer/par/innovus/defaults.yml
hammer/synthesis/genus/__init__.py
hammer/synthesis/genus/defaults.yml
hammer/tech/specialcells.py
hammer/vlsi/constraints.py
hammer/vlsi/hammer_tool.py
hammer/vlsi/hammer_vlsi_impl.py

Genus & Innovus are now combined under DDI starting with version 22.1.
Users of older Genus & Innovus versions will need to override the binary paths.
Genus clock mapping flow is now enabled if the additional special cells are specified.
Other small changes:
- Innovus flow effort defaults to standard (possibly a source of bad QoR in the past)
- Fix SDC quotations around paths for `get_port` for delay and load constraints
- Output load constraints should be specified as `CapacitanceValue`s
**Impact**:

Updates for DDI221

---

hammer/utils/lib_utils.py

Follow-on PR to #800. 
- Units Overhaul broke ASAP7, Sky130 flow (eg. in `e2e`,  fails after parsing lib `time_unit` to `"1ps";`)
- Fixes lib `time_unit` reading
- Some more pipe-cleaning is needed to check capacitance value reading
**Impact**:

Additional Units Overhaul Fixes

---

hammer/par/innovus/__init__.py

Not `-layers all` but `-all {route}`.
**Impact**:

Innovus: all layer obstruction flag

---

hammer/vlsi/hammer_vlsi_impl.py

Needed so that synthesis does not insert buffers
**Impact**:

set_dont_touch on preplaced pins in SDC file

---

hammer/sim/mocksim/__init__.py

HammerSimTool needs fill_outputs() 
**Impact**:

Mocksim was missing fill_outputs()

---

hammer/par/innovus/__init__.py
hammer/tech/stackup.py

- Cover blockage for PG nets up to top_layer-1 for hardmacros
- Remove `reset_db` for `add_stripes` attributes and remove antenna trimming (can be re-enabled in tech hooks, if required)
**Impact**:

Power straps updates

---

hammer/config/defaults.yml
hammer/config/defaults_types.yml
hammer/par/innovus/__init__.py
hammer/par/mockpar/__init__.py
hammer/par/nop/__init__.py
hammer/par/openroad/__init__.py
hammer/vlsi/hammer_vlsi_impl.py
hammer/vlsi/vendor/openroad.py

Default is stlil `stripe`, as before. This could be a way to fix some DRCs where trimming the strap back results in a bad via shape to the lower layer straps.
**Impact**:

Add setting to control antenna_trim_shape

---

hammer/synthesis/genus/__init__.py

With DDI, syn_generic uniquifies ILM module names. Prevent this by deuniquifying after syn_generic.
This also assumes that the type of hierarchical instances appears as `hierarchical` in the placement constraints.
Evidently this wasn't required before for the hierarchical flow to work correctly, but it is required for this fix to work.
**Impact**:

De-uniquify hierarchical blocks in genus for hierarchical flows

---

hammer/config/defaults.yml
hammer/config/defaults_types.yml
hammer/vlsi/hammer_vlsi_impl.py

In some technologies, the stdcell rail layer is handled by a special tech-specific hook. This gives us more flexibility in selecting which layers show up in the auto-generated power_straps.tcl
**Impact**:

Add flag to prevent power strap generation on stdcell rail layer

---

hammer/config/defaults.yml
hammer/config/defaults_types.yml
hammer/vlsi/hammer_vlsi_impl.py
tests/test_power_straps.py

The default setting "rail" uses the stdcell rail layer. This can be set to a different metal layer if desired
**Impact**:

Add bottom_via_layer API for power_straps.by_tracks

---

hammer/config/defaults.yml
hammer/config/defaults_types.yml
hammer/technology/sky130/defaults.yml
hammer/vlsi/constraints.py
hammer/vlsi/hammer_tool.py
hammer/vlsi/hammer_vlsi_impl.py
tests/test_power_straps.py

- Change `vlsi.inputs.supplies.power/ground.pin` to `.pins`. This generates CPFs with a `create_global_connection` from  single net to multiple pins
- Add `power_straps_options.by_tracks.power_nets` setting. This controls which supply nets power straps are generated for. The default uses all supplies, but this is not always desired
- Add `vlsi.input.supplies.power.voltage` field. The existing system would always create the power_nets with the same `vlsi.inputs.supplies.VDD` voltage. This enables per-supply voltage setting.
**Impact**:

Improvements to supplies API

---

hammer/logging/logging.py
hammer/vlsi/driver.py

Created atexit closing of hammer logging file in logging.py. 
fixes issue where logs are empty due to not closing the file before program terminates
- [ * ] Bug fix
**Impact**:
- [ * ] Other
- [ * ] Did you set `master` as the base branch?
- [ * ] Did you state the type-of-change/impact?
- [*  ] Did you delete any extraneous prints/debugging code?

hammer logging fixes

---

hammer/config/defaults.yml
hammer/par/innovus/__init__.py

Add top_layer/pg_pins_layers/stripe_pins flags to write_ilm for hierarchical flows

---

hammer/config/defaults.yml
hammer/synthesis/yosys/__init__.py
hammer/vlsi/constraints.py
hammer/vlsi/hammer_tool.py
hammer/vlsi/hammer_vlsi_impl.py
hammer/vlsi/vendor/openroad.py
tests/test_constraints.py

- Setup/hold delay constraints (-min/-max in SDC)
- Period is Optional for generated clocks
- Inverted clocks are done with `create_generated_clock -invert`. Negative divisors accomplish this.
- Small fix for Yosys uncertainty value
**Impact**:

Clock & Delay constraint refinements

---

e2e/Makefile
hammer/synthesis/genus/__init__.py

Added a clean rule to the e2e Makefile that deletes the build directory and all log files in the vlsi directory.
**Impact**:

Add make clean

---

hammer/synthesis/genus/__init__.py

Previously, #812 only dedups after `syn_generic`, but I found that sometimes, `syn_map` will also unnessarily uniquify ILMs. This adds the `dedup_ilm` step after both `syn_generic` and `syn_map`.
**Impact**:

Attempt to dedup ILMs after both syn_map and syn_generic

---

hammer/synthesis/genus/__init__.py

This is already done for the other Cadence tools. Setting this greatly improves SDC read time
**Impact**:

Genus: Set local multi_cpu_usage

---

hammer/vlsi/hammer_build_systems.py
tests/test_build_systems.py

Minor QoL improvement
**Impact**:

Add {redo-}hier-par-to-syn- targets to Makefile build flow

---

hammer/par/innovus/__init__.py

Addresses #820.
TLDR: Previously, top-level clock constraints weren't read until pre-CTS. Now, they are read pre-placement, so clock-aware placement can be performed.
#820
**Impact**:

Fix clock constraints not affecting place_opt

---

hammer/technology/sky130/extra/sram22/sram-cache.json
hammer/technology/sky130/sram-cache.json

Removed SRAMs from sram-cache.json that do not have LEFs as they cause errors during PAR.
**Impact**:

Fix SRAM22 `sram-cache.json` to exclude missing LEFs

---

hammer/tech/__init__.py

The surrounding accounts for a null `lib_corner`, but the pydantic type forces it to be (unnecessarily) non-null.
**Impact**:

minor: make lib_corner optional with default None

---

hammer/config/defaults.yml
hammer/config/defaults_types.yml
hammer/par/innovus/__init__.py
hammer/tech/stackup.py

- CPF intent can only be read when after ILM flattening. It is not possible to flatten ILMs before floorplanning. Hence, move the CPF read to later in the flow. 
-  Power straps continue to interact with routing within the halos. Proposed solution is like so: 1) Routing halo generation remains the same. Placement halo is slightly increased in size. A power routing blockage is then created in same shape as the placement halo. This allows router to avoid power straps in a non-routing-halo region, before subsequently entering the halo region (this seems to work better). Also, do this up to the top layer instead of layer-1.
- [X ] Bug fix
**Impact**:
- [X ] Change to a Hammer plugin
- [X ] Did you set `master` as the base …

Relocate CPF Read + Power Strap Issues

---

hammer/technology/sky130/__init__.py
hammer/technology/sky130/sky130.tech.json

SKY130 PDK fixes for Calibre and latest SKY130A release

---

hammer/common/cadence/__init__.py
hammer/config/defaults.yml
hammer/par/innovus/__init__.py
hammer/par/innovus/defaults.yml
hammer/par/openroad/__init__.py
hammer/power/joules/defaults.yml
hammer/synthesis/genus/__init__.py
hammer/synthesis/genus/defaults.yml
hammer/vlsi/constraints.py
hammer/vlsi/hammer_tool.py
tests/test_constraints.py

Genus enhancements:
- Fix `add_tieoffs` crashing because it got multiple lib cells. Now, we only get the specific lib cell for the current analysis view in MMMC mode.
- `report_timing -lint` for better info about missing SDC constraints
Many Innovus enhancements, including provisioning for updated commands in DDI 23.1:
- Check for any unplaced pins prior to cell placement, and error out if detected. Prevents cases where pins are erroneously routed to in the lower left corner (#834)
- Add soft (guide) and hard (region) placement constraint types
- Remove post-CTS timing reports from a separate folder (confusing)
- Enable `place_opt_design` version 2 - 25-30% runtime improvement for placement. `clock_opt_design` replaces `ccopt_design` in this flow.
- Fix SDF writing - timing values need to …

Many Genus + Innovus enhancements

---

hammer/par/innovus/__init__.py

Previously this was done before final DB was written, causing hierarchical flow to fail. Now only gets set in open_chip script if final db was run.
**Impact**:

Simultaneous setup/hold setting fix

---

hammer/vlsi/hammer_vlsi_impl.py

`get_ports` is the proper SDC command
`-add_delay` in `set_min/max_delay` allows you to constrain the same path against multiple clocks. Otherwise, second one overrides all previous declarations.
**Impact**:

Small SDC fixes

---

doc/Hammer-Use/Flowgraphs.rst
hammer/flowgraph/flowgraph.py
tests/test_flowgraph.py

This PR fixes several small bugs with the flowgraph frontend:
- If required output is set to <action>-output-full.json (like in Makefiles), it overwrites the full db with that of <action>-output.json (reduced)
- Child nodes’ required inputs get overridden by auto-inserted X-to-Y output, but we need to be able to have additional inputs
**Impact**:

Flowgraph fixes

---

doc/Hammer-Use/Hierarchical.rst
e2e/configs-design/pass/mock_hier.yml
e2e/configs-design/pass/mock_hier_addl.yml
e2e/configs-design/pass/mock_hier_legacy.yml
hammer/config/config_src.py
hammer/config/defaults.yml
hammer/config/defaults_types.yml
hammer/par/innovus/__init__.py
hammer/vlsi/cli_driver.py
hammer/vlsi/driver.py

It appears that #675 commented out #626, which was one step towards getting `vlsi.inputs.hierarchical.constraints` to support meta directives.
Now, module-level constraints can come from different files, as long as `vlsi.inputs.hierarchical.constraints_meta: append` is set. Each file can contain part of the constraints for a given module. This addresses most of #401 I believe.
Ran thru a quick e2e mock test:
```
hammer-vlsi -p configs-design/pass/mock_hier.yml -p configs-design/pass/mock_hier_addl.yml syn-SubModC
```
Reviewing `syn-SubModC/module_config.json` files shows the correct module-specific config and `syn-SubModC/syn-output-full.json` shows SubModC's specific `vlsi.inputs.hierchical.constraints` not making it through.
TODO:
Closes #401 …

Hier constraints from different files

---

hammer/synthesis/genus/__init__.py
hammer/synthesis/genus/defaults.yml

Hammer flow breaks on the physical-aware design flow in genus because genus only allows one file to be read for the qrc_tech_file attribute. To fix this, we have set this to always read the first index. We have also set the default value of the phys_flow_effort key to be none, and let the users decide the setting in their yml inputs.
**Impact**:

Fixing qrc tech file read bug in

---

hammer/synthesis/genus/__init__.py
hammer/synthesis/genus/defaults.yml

The command "write_db -common" is only necessary when doing physical aware flow. But even with the phys_flow_effort set to none, the command is written by default which breaks the genus synthesis flow. Added a condition to not use the command for non physical aware flow.  
**Impact**:

Write_db is not required for non physical aware flow

---

hammer/synthesis/yosys/__init__.py

Right now if a technology doesn't specify the latch map file, "techmap -map None" is written into the generated tcl.
**Type of change**: Bugfix
**Impact**:  Change to a Hammer plugin

Make latch_map_file truly optional

---

hammer/synthesis/yosys/__init__.py

Remove `-map-only` flag that was breaking synthesis, causing many DFFs to be emitted as Yosys internal abstract cells instead of being mapped to the available DFF cells.
**Impact**:

Fix Yosys DFF mapping

---

hammer/technology/sky130/README.md

Minor documentation for sky130.
**Impact**:

sky130: documentation updates

---

hammer/lvs/icv/__init__.py
hammer/synthesis/genus/__init__.py
hammer/utils/__init__.py

Commit: [/synthesis/genus make run_genus a distinct step](https://github.com/ucb-bar/hammer/commit/d326d697153b13142c8f757dd7dfc0ba6b0d9cd3)
- This is useful/necessary for hooks which inject behaviors AFTER the syn.tcl file has been generated.
Commit: [lvs/icv add lvs.icv.equiv_files for blackboxes](https://github.com/ucb-bar/hammer/commit/20691d568ae1d2e785ab2e36257017066a8c90f2)
- Equivalence files are used by ICV LVS to define LVS boxes/blackboxes. This is an extremeley useful feature for debugging LVS & running LVS quickly.
Commit: [utils/ get_filetype add ".net" as supported ext.](https://github.com/ucb-bar/hammer/commit/b59a3b1a10735d649b12907f24b86e25cecd14df)
- Cadence Virtuoso will produce netlists with the .src.net extension when streaming out schematics as netlists (i.e. when …

Distinct `run_genus` synthesis step, ICV LVS blackbox support, and Virtuoso netlist export support

---

hammer/par/innovus/__init__.py

While I understand this is space-efficient to export the final database as a `.gds.gz`, this change (introduced in 5e3cfb37bd5ede464769479889bb6ad38e2509e6 )  significantly breaks the hammer-intech22-plugin fill.mk and icv.mk scripts. See the image below regarding how it breaks the plugin.
This PR reverts the change, so Innovus will export a `.gds` instead of `.gds.gz`
The fix could occur on either the hammer-intech22-plugin side, or here. I leave that to the maintainers to decide which is best ;) 
N/A
**Impact**:

par/innovus revert gds.gz output gds extension

---

hammer/common/cadence/__init__.py
hammer/generate_properties.py
hammer/par/innovus/__init__.py
hammer/timing/tempus/__init__.py
hammer/timing/tempus/defaults.yml
hammer/vlsi/driver.py
hammer/vlsi/hammer_vlsi_impl.py

Fixes issues with the STA flow using Innovus and Tempus.
**Impact**:

P&R timing flow for Innovus/Tempus

---

.readthedocs.yml

Pin the poetry version to 1.5.1, which is known to work well with ReadTheDocs Explicitly install virtualenv 20.23.1, which doesn't have the issue with the 'free_threaded' attribute
Ideally fixes the failing check in https://github.com/ucb-bar/hammer/pull/886
(tangential to the contents of that PR)
**Impact**:

Fix Read the Docs build environment

---

hammer/config/config_src.py

It is common to define paths to collateral files with environment variables, but currently if you include paths in your config/spec .yml file that use environment vars, you will get an error.
Consider the following example, I would like to add a new library to `vlsi.technology.extra_libraries`:
**Spec.yml**
```
vlsi.technology.extra_libraries:
- library:
gds_file: "$WORK_DIR/vlsi/sensor_adc_top.gds"
lef_file: "$WORK_DIR/vlsi/sensor_adc_top_abstract.lef"
verilog_synth: "$CHIP/vlsi/collaterals/utilities/scumvtop_gen/SENSOR_PLACE.v"
nldm_liberty_file: "$WORK_DIR/vlsi/sensor_adc_top.lib"
spice_file: "$CHIP/vlsi/collaterals/spice_netlists/SENSOR_PLACE.src.net"
```
If I attempt any operation using this library, I will get a ValueError because the envvars are not expanded
```
ValueError: Path …
```

Expand environment variables in configuration files

---

hammer/common/synopsys/__init__.py
hammer/drc/icv/defaults.yml
hammer/lvs/icv/defaults.yml
tests/test_synopsys_tool.py

The BWRC servers migrated to RHEL9, and with that, our old setup using S-2021.06-SP3-2 for the default ICV version is not functional.
In general, users of RHEL9 should adopt W-2024.09-4 for ICV and V-2023.09-SP2 for ICVWB.
Synopsys now defaults to install these newer ICV versions at the /icvalidator/ directory instead of /icv/, so the ICV_HOME env var should reflect this.
Finally, SynopsysTool.version_number() fails to correctly parse W-2024.09-4:
This change fixes that, and includes regression unit tests to ensure previous versions of ICV can still be successfully parsed
Related to this PR for hammer-intech22-plugin https://bwrcrepo.eecs.berkeley.edu/intech22/hammer-intech22-plugin/-/merge_requests/72
**Impact**:

Update ICV defaults for RHEL9, fix version_number()

---

hammer/vlsi/hammer_vlsi_impl.py

Fixes a print statement that would always fail
due to `len(above_insts)` being equal to 0.
**Impact**:

Fix failing print statement warning about lack of power straps
